version: '3'
services:
  database:
    image: mariadb:latest
    environment:
    - MYSQL_ROOT_PASSWORD=kuman-db-password
    - MYSQL_DATABASE=kuman
    ports:
    - 3306:3306
    volumes: 
    - kuman-data:/data
volumes:
  kuman-data: {}
