version: '3'
services:
  database:
    image: mariadb:latest
    environment:
    - MYSQL_ROOT_PASSWORD: kuman-db-password
    - MYSQL_DATABASE: kuman
  volumes:
    - kuman-data:/data
volumns:
  kuman-data: {}
